### ISSUE TITLE
Unable to load model files

### ISSUE THREAD

**Issue by mwhstudio** [dsuarezv/myarmui#1]
System.Exception
  HResult=0x80131500
  Message=Could not load mesh LocalDepot/right.model
  Source=Engine.Core
  StackTrace:
   at Engine.Core.Assert.IsNotNull(Object objectToCheck, String msg, Object[] args)
   at Engine.Core.MeshRenderer.Setup()
   at Engine.Core.Component.PerformSetup()
   at Engine.Core.Component.set_Entity(Entity value)
   at Engine.Core.Entity.AddComponent(Component c)
   at MyArmUI.SceneHandler.Setup() in D:\Monkey3DOpenTK\myarmui-devel\MyArmUI\SceneHandler.cs:line 72
   at MyArmUI.MainForm.View3d_SceneLoad(Object arg1, EventArgs arg2) in D:\Monkey3DOpenTK\myarmui-devel\MyArmUI\MainForm.cs:line 48
   at Engine.WinFormsControl.EngineControl.SetupScene()
   at Engine.WinFormsControl.EngineControl.Glc_Load(Object sender, EventArgs e)
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.UserControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at Engine.WinFormsControl.EngineControl.InitializeGLControl()
   at Engine.WinFormsControl.EngineControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by PandaUnit-TWL** [comment]
Same
